"""create intake and proposal tables

Revision ID: e10f37eda6f1
Revises: 
Create Date: 2026-09-09 02:53:45.832842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10f37eda6f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATING', 'GENERATION_FAILED', 'IN_REVIEW', 'PENDING_APPROVAL', 'APPROVED', 'DOCUMENT_GENERATING', 'DOCUMENT_GENERATION_FAILED', 'DOCUMENT_READY', 'DELIVERING', 'DELIVERY_FAILED', 'DELIVERED', 'REJECTED', 'CLOSED', name='proposalstatus', native_enum=False), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('salesperson_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_call', sa.String(length=100), nullable=False),
    sa.Column('client_needs_summary', sa.Text(), nullable=False),
    sa.Column('project_scope', sa.Text(), nullable=False),
    sa.Column('goals_and_objectives', sa.Text(), nullable=False),
    sa.Column('recommended_services', sa.Text(), nullable=False),
    sa.Column('proposed_timeline', sa.Text(), nullable=False),
    sa.Column('estimated_pricing', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intake_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intake_key', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id')
    )
    op.create_index(op.f('ix_intake_submissions_intake_key'), 'intake_submissions', ['intake_key'], unique=True)
    op.create_table('proposal_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('section_key', sa.Enum('INTRODUCTION', 'PROPOSED_SOLUTION', 'DELIVERABLES', 'TIMELINE', 'PRICING', 'NEXT_STEPS', name='sectionkey', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_origin', sa.Enum('TEMPLATE_DEFAULT', 'AI_GENERATED', 'HUMAN_EDITED', 'HUMAN_EDITED_AFTER_GENERATION', name='contentorigin', native_enum=False), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', name='sectionapprovalstatus', native_enum=False), nullable=False),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_sections_proposal_id'), 'proposal_sections', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_sections_proposal_id'), table_name='proposal_sections')
    op.drop_table('proposal_sections')
    op.drop_index(op.f('ix_intake_submissions_intake_key'), table_name='intake_submissions')
    op.drop_table('intake_submissions')
    op.drop_table('proposals')
    # ### end Alembic commands ###
